#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# aliases
alias hop="ssh -C -t hop /usr/bin/screen -xRR"

# Haskell
export PATH="$PATH:$HOME/.cabal/bin"

# NPM
export PATH="/usr/local/share/npm/bin:$PATH"

# TeX
export PATH="$PATH:/usr/texbin"

# RVM
export PATH="$HOME/.rvm/bin:$PATH"

# added by travis gem
[ -f /Users/stask/.travis/travis.sh ] && source /Users/stask/.travis/travis.sh
